---
sudo: false
language: python

python: "3.7"

env:
  global:
    - DATABASE_URL='postgres://postgres@localhost/forkit'
  matrix:
    - TOXENV=py27-django18
    - TOXENV=py27-django19
    - TOXENV=py27-django110
    - TOXENV=py27-django111
    - TOXENV=py37-django111
    - TOXENV=py37-django20
    - TOXENV=py37-django21

services:
  - postgres

fast_finish: true

cache: pip

before_install:
  - psql -c 'CREATE DATABASE forkit;' -U postgres

install:
  - pip install --upgrade pip wheel setuptools
  - pip install tox

script:
  - tox

notifications:
  email: false
